package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private AddressId id;
     private City cityByProvinceId;
     private City cityByCityId;
     private City cityBySuburbId;
     private Customer customer;
     private String address;
     private String address2;
     private String postcode;
     private String phone;
     private boolean active;
     private Date lastUpdate;

    public Address() {
    }

	
    public Address(AddressId id, City cityByProvinceId, City cityByCityId, City cityBySuburbId, Customer customer, String address, String postcode, String phone, boolean active, Date lastUpdate) {
        this.id = id;
        this.cityByProvinceId = cityByProvinceId;
        this.cityByCityId = cityByCityId;
        this.cityBySuburbId = cityBySuburbId;
        this.customer = customer;
        this.address = address;
        this.postcode = postcode;
        this.phone = phone;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Address(AddressId id, City cityByProvinceId, City cityByCityId, City cityBySuburbId, Customer customer, String address, String address2, String postcode, String phone, boolean active, Date lastUpdate) {
       this.id = id;
       this.cityByProvinceId = cityByProvinceId;
       this.cityByCityId = cityByCityId;
       this.cityBySuburbId = cityBySuburbId;
       this.customer = customer;
       this.address = address;
       this.address2 = address2;
       this.postcode = postcode;
       this.phone = phone;
       this.active = active;
       this.lastUpdate = lastUpdate;
    }
   
    public AddressId getId() {
        return this.id;
    }
    
    public void setId(AddressId id) {
        this.id = id;
    }
    public City getCityByProvinceId() {
        return this.cityByProvinceId;
    }
    
    public void setCityByProvinceId(City cityByProvinceId) {
        this.cityByProvinceId = cityByProvinceId;
    }
    public City getCityByCityId() {
        return this.cityByCityId;
    }
    
    public void setCityByCityId(City cityByCityId) {
        this.cityByCityId = cityByCityId;
    }
    public City getCityBySuburbId() {
        return this.cityBySuburbId;
    }
    
    public void setCityBySuburbId(City cityBySuburbId) {
        this.cityBySuburbId = cityBySuburbId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


