package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Short cardId;
     private String cardNumber;
     private byte[] frontPicture;
     private byte[] backPicture;
     private String filePathFront;
     private String filePathBack;
     private Set customers = new HashSet(0);

    public Card() {
    }

	
    public Card(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public Card(String cardNumber, byte[] frontPicture, byte[] backPicture, String filePathFront,String filePathBack, Set customers) {
       this.cardNumber = cardNumber;
       this.frontPicture = frontPicture;
       this.backPicture = backPicture;
       this.filePathFront = filePathFront;
       this.filePathBack = filePathBack;
       this.customers = customers;
    }
   
    public Short getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Short cardId) {
        this.cardId = cardId;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public byte[] getFrontPicture() {
        return this.frontPicture;
    }
    
    public void setFrontPicture(byte[] frontPicture) {
        this.frontPicture = frontPicture;
    }
    public byte[] getBackPicture() {
        return this.backPicture;
    }
    
    public void setBackPicture(byte[] backPicture) {
        this.backPicture = backPicture;
    }

    public String getFilePathFront() {
        return filePathFront;
    }

    public void setFilePathFront(String filePathFront) {
        this.filePathFront = filePathFront;
    }

    public String getFilePathBack() {
        return filePathBack;
    }

    public void setFilePathBack(String filePathBack) {
        this.filePathBack = filePathBack;
    }
  
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


