package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Short cardId;
     private Customer customer;
     private String cardNumber;
     private byte[] frontPicture;
     private byte[] backPicture;
     private String filePathFront;
     private String filePathBack;
     private Date lastUpdate;

    public Card() {
    }

	
    public Card(Customer customer, String cardNumber, Date lastUpdate) {
        this.customer = customer;
        this.cardNumber = cardNumber;
        this.lastUpdate = lastUpdate;
    }
    public Card(Customer customer, String cardNumber, byte[] frontPicture, byte[] backPicture, String filePathFront, String filePathBack, Date lastUpdate) {
       this.customer = customer;
       this.cardNumber = cardNumber;
       this.frontPicture = frontPicture;
       this.backPicture = backPicture;
       this.filePathFront = filePathFront;
       this.filePathBack = filePathBack;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Short cardId) {
        this.cardId = cardId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public byte[] getFrontPicture() {
        return this.frontPicture;
    }
    
    public void setFrontPicture(byte[] frontPicture) {
        this.frontPicture = frontPicture;
    }
    public byte[] getBackPicture() {
        return this.backPicture;
    }
    
    public void setBackPicture(byte[] backPicture) {
        this.backPicture = backPicture;
    }
    public String getFilePathFront() {
        return this.filePathFront;
    }
    
    public void setFilePathFront(String filePathFront) {
        this.filePathFront = filePathFront;
    }
    public String getFilePathBack() {
        return this.filePathBack;
    }
    
    public void setFilePathBack(String filePathBack) {
        this.filePathBack = filePathBack;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


