package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Short cardId;
     private String cardNumber;
     private byte[] frontPicture;
     private byte[] backPicture;
     private String filePath;
     private Set customers = new HashSet(0);

    public Card() {
    }

	
    public Card(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public Card(String cardNumber, byte[] frontPicture, byte[] backPicture, String filePath, Set customers) {
       this.cardNumber = cardNumber;
       this.frontPicture = frontPicture;
       this.backPicture = backPicture;
       this.filePath = filePath;
       this.customers = customers;
    }
   
    public Short getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Short cardId) {
        this.cardId = cardId;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public byte[] getFrontPicture() {
        return this.frontPicture;
    }
    
    public void setFrontPicture(byte[] frontPicture) {
        this.frontPicture = frontPicture;
    }
    public byte[] getBackPicture() {
        return this.backPicture;
    }
    
    public void setBackPicture(byte[] backPicture) {
        this.backPicture = backPicture;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


