package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Byte categoryId;
     private String categoryName;
     private Date lastUpdate;
     private Set products = new HashSet(0);

    public Category() {
    }

	
    public Category(String categoryName, Date lastUpdate) {
        this.categoryName = categoryName;
        this.lastUpdate = lastUpdate;
    }
    public Category(String categoryName, Date lastUpdate, Set products) {
       this.categoryName = categoryName;
       this.lastUpdate = lastUpdate;
       this.products = products;
    }
   
    public Byte getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Byte categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


