package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Short cityId;
     private short parentId;
     private String name;
     private boolean type;
     private Date lastUpdate;
     private Set addressesForSuburbId = new HashSet(0);
     private Set addressesForCityId = new HashSet(0);
     private Set addressesForProvinceId = new HashSet(0);

    public City() {
    }

	
    public City(short parentId, String name, boolean type, Date lastUpdate) {
        this.parentId = parentId;
        this.name = name;
        this.type = type;
        this.lastUpdate = lastUpdate;
    }
    public City(short parentId, String name, boolean type, Date lastUpdate, Set addressesForSuburbId, Set addressesForCityId, Set addressesForProvinceId) {
       this.parentId = parentId;
       this.name = name;
       this.type = type;
       this.lastUpdate = lastUpdate;
       this.addressesForSuburbId = addressesForSuburbId;
       this.addressesForCityId = addressesForCityId;
       this.addressesForProvinceId = addressesForProvinceId;
    }
   
    public Short getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }
    public short getParentId() {
        return this.parentId;
    }
    
    public void setParentId(short parentId) {
        this.parentId = parentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isType() {
        return this.type;
    }
    
    public void setType(boolean type) {
        this.type = type;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getAddressesForSuburbId() {
        return this.addressesForSuburbId;
    }
    
    public void setAddressesForSuburbId(Set addressesForSuburbId) {
        this.addressesForSuburbId = addressesForSuburbId;
    }
    public Set getAddressesForCityId() {
        return this.addressesForCityId;
    }
    
    public void setAddressesForCityId(Set addressesForCityId) {
        this.addressesForCityId = addressesForCityId;
    }
    public Set getAddressesForProvinceId() {
        return this.addressesForProvinceId;
    }
    
    public void setAddressesForProvinceId(Set addressesForProvinceId) {
        this.addressesForProvinceId = addressesForProvinceId;
    }




}


