package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Short customerId;
     private Card card;
     private String customerName;
     private String email;
     private boolean active;
     private Date createDate;
     private Date lastUpdate;
     private Set addresses = new HashSet(0);
     private Set orders = new HashSet(0);

    public Customer() {
    }

	
    public Customer(Card card, String customerName, boolean active, Date createDate) {
        this.card = card;
        this.customerName = customerName;
        this.active = active;
        this.createDate = createDate;
    }
    public Customer(Card card, String customerName, String email, boolean active, Date createDate, Date lastUpdate, Set addresses, Set orders) {
       this.card = card;
       this.customerName = customerName;
       this.email = email;
       this.active = active;
       this.createDate = createDate;
       this.lastUpdate = lastUpdate;
       this.addresses = addresses;
       this.orders = orders;
    }
   
    public Short getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


