package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Logistics generated by hbm2java
 */
public class Logistics  implements java.io.Serializable {


     private Short companyId;
     private String companyName;
     private String phone;
     private Date lastUpdate;
     private Set shippments = new HashSet(0);

    public Logistics() {
    }

	
    public Logistics(String companyName) {
        this.companyName = companyName;
    }
    public Logistics(String companyName, String phone, Date lastUpdate, Set shippments) {
       this.companyName = companyName;
       this.phone = phone;
       this.lastUpdate = lastUpdate;
       this.shippments = shippments;
    }
   
    public Short getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Short companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getShippments() {
        return this.shippments;
    }
    
    public void setShippments(Set shippments) {
        this.shippments = shippments;
    }




}


