package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA



/**
 * OrderProductId generated by hbm2java
 */
public class OrderProductId  implements java.io.Serializable {


     private int orderId;
     private short productId;

    public OrderProductId() {
    }

    public OrderProductId(int orderId, short productId) {
       this.orderId = orderId;
       this.productId = productId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public short getProductId() {
        return this.productId;
    }
    
    public void setProductId(short productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderProductId) ) return false;
		 OrderProductId castOther = ( OrderProductId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


