package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderProduct generated by hbm2java
 */
public class OrderProduct  implements java.io.Serializable {


     private OrderProductId id;
     private Order order;
     private Product product;
     private Short quantity;
     private BigDecimal unitPrice;
     private Date lastUpdate;

    public OrderProduct() {
    }

	
    public OrderProduct(OrderProductId id, Order order, Product product, Date lastUpdate) {
        this.id = id;
        this.order = order;
        this.product = product;
        this.lastUpdate = lastUpdate;
    }
    public OrderProduct(OrderProductId id, Order order, Product product, Short quantity, BigDecimal unitPrice, Date lastUpdate) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.lastUpdate = lastUpdate;
    }
   
    public OrderProductId getId() {
        return this.id;
    }
    
    public void setId(OrderProductId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


