package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Customer customer;
     private Date orderDate;
     private Date lastUpdate;
     private Set orderProducts = new HashSet(0);
     private Set shippmentOrders = new HashSet(0);
     private Set payments = new HashSet(0);

    public Order() {
    }

	
    public Order(Customer customer, Date orderDate, Date lastUpdate) {
        this.customer = customer;
        this.orderDate = orderDate;
        this.lastUpdate = lastUpdate;
    }
    public Order(Customer customer, Date orderDate, Date lastUpdate, Set orderProducts, Set shippmentOrders, Set payments) {
       this.customer = customer;
       this.orderDate = orderDate;
       this.lastUpdate = lastUpdate;
       this.orderProducts = orderProducts;
       this.shippmentOrders = shippmentOrders;
       this.payments = payments;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getOrderProducts() {
        return this.orderProducts;
    }
    
    public void setOrderProducts(Set orderProducts) {
        this.orderProducts = orderProducts;
    }
    public Set getShippmentOrders() {
        return this.shippmentOrders;
    }
    
    public void setShippmentOrders(Set shippmentOrders) {
        this.shippmentOrders = shippmentOrders;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


