package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1



/**
 * OrderPaymentId generated by hbm2java
 */
public class OrderPaymentId  implements java.io.Serializable {


     private int orderId;
     private short paymentOrdinal;

    public OrderPaymentId() {
    }

    public OrderPaymentId(int orderId, short paymentOrdinal) {
       this.orderId = orderId;
       this.paymentOrdinal = paymentOrdinal;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public short getPaymentOrdinal() {
        return this.paymentOrdinal;
    }
    
    public void setPaymentOrdinal(short paymentOrdinal) {
        this.paymentOrdinal = paymentOrdinal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderPaymentId) ) return false;
		 OrderPaymentId castOther = ( OrderPaymentId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getPaymentOrdinal()==castOther.getPaymentOrdinal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getPaymentOrdinal();
         return result;
   }   


}


