package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Customer customer;
     private Date orderPlacedDate;
     private boolean active;
     private Date orderCompleteDate;
     private Date lastUpdate;
     private Set orderProducts = new HashSet(0);
     private Set orderPayments = new HashSet(0);
     private Set orderShippments = new HashSet(0);

    public Order() {
    }

	
    public Order(Customer customer, Date orderPlacedDate, boolean active, Date lastUpdate) {
        this.customer = customer;
        this.orderPlacedDate = orderPlacedDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Order(Customer customer, Date orderPlacedDate, boolean active, Date orderCompleteDate, Date lastUpdate, Set orderProducts, Set orderPayments, Set orderShippments) {
       this.customer = customer;
       this.orderPlacedDate = orderPlacedDate;
       this.active = active;
       this.orderCompleteDate = orderCompleteDate;
       this.lastUpdate = lastUpdate;
       this.orderProducts = orderProducts;
       this.orderPayments = orderPayments;
       this.orderShippments = orderShippments;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getOrderPlacedDate() {
        return this.orderPlacedDate;
    }
    
    public void setOrderPlacedDate(Date orderPlacedDate) {
        this.orderPlacedDate = orderPlacedDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getOrderCompleteDate() {
        return this.orderCompleteDate;
    }
    
    public void setOrderCompleteDate(Date orderCompleteDate) {
        this.orderCompleteDate = orderCompleteDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getOrderProducts() {
        return this.orderProducts;
    }
    
    public void setOrderProducts(Set orderProducts) {
        this.orderProducts = orderProducts;
    }
    public Set getOrderPayments() {
        return this.orderPayments;
    }
    
    public void setOrderPayments(Set orderPayments) {
        this.orderPayments = orderPayments;
    }
    public Set getOrderShippments() {
        return this.orderShippments;
    }
    
    public void setOrderShippments(Set orderShippments) {
        this.orderShippments = orderShippments;
    }




}


