package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderShippment generated by hbm2java
 */
public class OrderShippment  implements java.io.Serializable {


     private Short orderShippmentId;
     private Order order;
     private Shippment shippment;
     private Date lastUpdate;

    public OrderShippment() {
    }

	
    public OrderShippment(Order order, Shippment shippment) {
        this.order = order;
        this.shippment = shippment;
    }
    public OrderShippment(Order order, Shippment shippment, Date lastUpdate) {
       this.order = order;
       this.shippment = shippment;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getOrderShippmentId() {
        return this.orderShippmentId;
    }
    
    public void setOrderShippmentId(Short orderShippmentId) {
        this.orderShippmentId = orderShippmentId;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Shippment getShippment() {
        return this.shippment;
    }
    
    public void setShippment(Shippment shippment) {
        this.shippment = shippment;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


