package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA



/**
 * PaymentId generated by hbm2java
 */
public class PaymentId  implements java.io.Serializable {


     private int orderId;
     private short paymentOrdinal;

    public PaymentId() {
    }

    public PaymentId(int orderId, short paymentOrdinal) {
       this.orderId = orderId;
       this.paymentOrdinal = paymentOrdinal;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public short getPaymentOrdinal() {
        return this.paymentOrdinal;
    }
    
    public void setPaymentOrdinal(short paymentOrdinal) {
        this.paymentOrdinal = paymentOrdinal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaymentId) ) return false;
		 PaymentId castOther = ( PaymentId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getPaymentOrdinal()==castOther.getPaymentOrdinal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getPaymentOrdinal();
         return result;
   }   


}


