package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private PaymentId id;
     private Order order;
     private BigDecimal amount;
     private Date paymentDate;
     private String paymentMethod;
     private Date lastUpdate;

    public Payment() {
    }

	
    public Payment(PaymentId id, Order order, BigDecimal amount) {
        this.id = id;
        this.order = order;
        this.amount = amount;
    }
    public Payment(PaymentId id, Order order, BigDecimal amount, Date paymentDate, String paymentMethod, Date lastUpdate) {
       this.id = id;
       this.order = order;
       this.amount = amount;
       this.paymentDate = paymentDate;
       this.paymentMethod = paymentMethod;
       this.lastUpdate = lastUpdate;
    }
   
    public PaymentId getId() {
        return this.id;
    }
    
    public void setId(PaymentId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


