package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Procurement generated by hbm2java
 */
public class Procurement  implements java.io.Serializable {


     private Short procurementId;
     private Date procurementDate;
     private Date lastUpdate;
     private Set productProcurements = new HashSet(0);

    public Procurement() {
    }

	
    public Procurement(Date procurementDate, Date lastUpdate) {
        this.procurementDate = procurementDate;
        this.lastUpdate = lastUpdate;
    }
    public Procurement(Date procurementDate, Date lastUpdate, Set productProcurements) {
       this.procurementDate = procurementDate;
       this.lastUpdate = lastUpdate;
       this.productProcurements = productProcurements;
    }
   
    public Short getProcurementId() {
        return this.procurementId;
    }
    
    public void setProcurementId(Short procurementId) {
        this.procurementId = procurementId;
    }
    public Date getProcurementDate() {
        return this.procurementDate;
    }
    
    public void setProcurementDate(Date procurementDate) {
        this.procurementDate = procurementDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getProductProcurements() {
        return this.productProcurements;
    }
    
    public void setProductProcurements(Set productProcurements) {
        this.productProcurements = productProcurements;
    }




}


