package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Procurement generated by hbm2java
 */
public class Procurement  implements java.io.Serializable {


     private Short procurementId;
     private Date procurementDate;
     private char archvFlag;
     private Date lastUpdate;
     private Set productProcurements = new HashSet(0);

    public Procurement() {
    }

	
    public Procurement(Date procurementDate, char archvFlag, Date lastUpdate) {
        this.procurementDate = procurementDate;
        this.archvFlag = archvFlag;
        this.lastUpdate = lastUpdate;
    }
    public Procurement(Date procurementDate, char archvFlag, Date lastUpdate, Set productProcurements) {
       this.procurementDate = procurementDate;
       this.archvFlag = archvFlag;
       this.lastUpdate = lastUpdate;
       this.productProcurements = productProcurements;
    }
   
    public Short getProcurementId() {
        return this.procurementId;
    }
    
    public void setProcurementId(Short procurementId) {
        this.procurementId = procurementId;
    }
    public Date getProcurementDate() {
        return this.procurementDate;
    }
    
    public void setProcurementDate(Date procurementDate) {
        this.procurementDate = procurementDate;
    }
    public char getArchvFlag() {
        return this.archvFlag;
    }
    
    public void setArchvFlag(char archvFlag) {
        this.archvFlag = archvFlag;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getProductProcurements() {
        return this.productProcurements;
    }
    
    public void setProductProcurements(Set productProcurements) {
        this.productProcurements = productProcurements;
    }




}


