package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductProcurement generated by hbm2java
 */
public class ProductProcurement  implements java.io.Serializable {


     private Short id;
     private Procurement procurement;
     private Product product;
     private short quantity;
     private BigDecimal unitPrice;
     private Date lastUpdate;

    public ProductProcurement() {
    }

    public ProductProcurement(Procurement procurement, Product product, short quantity, BigDecimal unitPrice, Date lastUpdate) {
       this.procurement = procurement;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public Procurement getProcurement() {
        return this.procurement;
    }
    
    public void setProcurement(Procurement procurement) {
        this.procurement = procurement;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


