package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1



/**
 * ProductText generated by hbm2java
 */
public class ProductText  implements java.io.Serializable {


     private short productId;
     private String productName;
     private String description;

    public ProductText() {
    }

	
    public ProductText(short productId, String productName) {
        this.productId = productId;
        this.productName = productName;
    }
    public ProductText(short productId, String productName, String description) {
       this.productId = productId;
       this.productName = productName;
       this.description = description;
    }
   
    public short getProductId() {
        return this.productId;
    }
    
    public void setProductId(short productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


