package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReferenceValues generated by hbm2java
 */
public class ReferenceValues  implements java.io.Serializable {


     private Short rfvalRefno;
     private String rfvdmCode;
     private String description;
     private String mainCode;
     private Character archvFlag;
     private Date lastUpdate;

    public ReferenceValues() {
    }

	
    public ReferenceValues(String rfvdmCode, String description, String mainCode) {
        this.rfvdmCode = rfvdmCode;
        this.description = description;
        this.mainCode = mainCode;
    }
    public ReferenceValues(String rfvdmCode, String description, String mainCode, Character archvFlag, Date lastUpdate) {
       this.rfvdmCode = rfvdmCode;
       this.description = description;
       this.mainCode = mainCode;
       this.archvFlag = archvFlag;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getRfvalRefno() {
        return this.rfvalRefno;
    }
    
    public void setRfvalRefno(Short rfvalRefno) {
        this.rfvalRefno = rfvalRefno;
    }
    public String getRfvdmCode() {
        return this.rfvdmCode;
    }
    
    public void setRfvdmCode(String rfvdmCode) {
        this.rfvdmCode = rfvdmCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMainCode() {
        return this.mainCode;
    }
    
    public void setMainCode(String mainCode) {
        this.mainCode = mainCode;
    }
    public Character getArchvFlag() {
        return this.archvFlag;
    }
    
    public void setArchvFlag(Character archvFlag) {
        this.archvFlag = archvFlag;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


