package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReferenceValuesDomains generated by hbm2java
 */
public class ReferenceValuesDomains  implements java.io.Serializable {


     private Short rfvdmRefno;
     private String rfvdmCode;
     private String description;
     private char archvFlag;
     private Date lastUpdate;

    public ReferenceValuesDomains() {
    }

	
    public ReferenceValuesDomains(String rfvdmCode, String description, char archvFlag) {
        this.rfvdmCode = rfvdmCode;
        this.description = description;
        this.archvFlag = archvFlag;
    }
    public ReferenceValuesDomains(String rfvdmCode, String description, char archvFlag, Date lastUpdate) {
       this.rfvdmCode = rfvdmCode;
       this.description = description;
       this.archvFlag = archvFlag;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getRfvdmRefno() {
        return this.rfvdmRefno;
    }
    
    public void setRfvdmRefno(Short rfvdmRefno) {
        this.rfvdmRefno = rfvdmRefno;
    }
    public String getRfvdmCode() {
        return this.rfvdmCode;
    }
    
    public void setRfvdmCode(String rfvdmCode) {
        this.rfvdmCode = rfvdmCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getArchvFlag() {
        return this.archvFlag;
    }
    
    public void setArchvFlag(char archvFlag) {
        this.archvFlag = archvFlag;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


