package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Shippment generated by hbm2java
 */
public class Shippment  implements java.io.Serializable {


     private Short shippmentId;
     private Logistics logistics;
     private String trackNumber;
     private BigDecimal postage;
     private Date shippedDate;
     private Date signedoffDate;
     private Date lastUpdate;
     private Set shippmentOrders = new HashSet(0);

    public Shippment() {
    }

	
    public Shippment(Logistics logistics, String trackNumber, BigDecimal postage, Date shippedDate) {
        this.logistics = logistics;
        this.trackNumber = trackNumber;
        this.postage = postage;
        this.shippedDate = shippedDate;
    }
    public Shippment(Logistics logistics, String trackNumber, BigDecimal postage, Date shippedDate, Date signedoffDate, Date lastUpdate, Set shippmentOrders) {
       this.logistics = logistics;
       this.trackNumber = trackNumber;
       this.postage = postage;
       this.shippedDate = shippedDate;
       this.signedoffDate = signedoffDate;
       this.lastUpdate = lastUpdate;
       this.shippmentOrders = shippmentOrders;
    }
   
    public Short getShippmentId() {
        return this.shippmentId;
    }
    
    public void setShippmentId(Short shippmentId) {
        this.shippmentId = shippmentId;
    }
    public Logistics getLogistics() {
        return this.logistics;
    }
    
    public void setLogistics(Logistics logistics) {
        this.logistics = logistics;
    }
    public String getTrackNumber() {
        return this.trackNumber;
    }
    
    public void setTrackNumber(String trackNumber) {
        this.trackNumber = trackNumber;
    }
    public BigDecimal getPostage() {
        return this.postage;
    }
    
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }
    public Date getSignedoffDate() {
        return this.signedoffDate;
    }
    
    public void setSignedoffDate(Date signedoffDate) {
        this.signedoffDate = signedoffDate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getShippmentOrders() {
        return this.shippmentOrders;
    }
    
    public void setShippmentOrders(Set shippmentOrders) {
        this.shippmentOrders = shippmentOrders;
    }




}


