package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Shippment generated by hbm2java
 */
public class Shippment  implements java.io.Serializable {


     private Short shippmentId;
     private Logistics logistics;
     private String trackNumber;
     private BigDecimal postage;
     private BigDecimal weight;
     private Date shippedDate;
     private String fromLocation;
     private String toLocation;
     private String status;
     private Date signedoffDate;
     private String signedoffPerson;
     private String notes;
     private boolean active;
     private Date lastUpdate;
     private Set orderShippments = new HashSet(0);

    public Shippment() {
    }

	
    public Shippment(Logistics logistics, String trackNumber, BigDecimal postage, Date shippedDate, boolean active) {
        this.logistics = logistics;
        this.trackNumber = trackNumber;
        this.postage = postage;
        this.shippedDate = shippedDate;
        this.active = active;
    }
    public Shippment(Logistics logistics, String trackNumber, BigDecimal postage, BigDecimal weight, Date shippedDate, String fromLocation, String toLocation, String status, Date signedoffDate, String signedoffPerson, String notes, boolean active, Date lastUpdate, Set orderShippments) {
       this.logistics = logistics;
       this.trackNumber = trackNumber;
       this.postage = postage;
       this.weight = weight;
       this.shippedDate = shippedDate;
       this.fromLocation = fromLocation;
       this.toLocation = toLocation;
       this.status = status;
       this.signedoffDate = signedoffDate;
       this.signedoffPerson = signedoffPerson;
       this.notes = notes;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.orderShippments = orderShippments;
    }
   
    public Short getShippmentId() {
        return this.shippmentId;
    }
    
    public void setShippmentId(Short shippmentId) {
        this.shippmentId = shippmentId;
    }
    public Logistics getLogistics() {
        return this.logistics;
    }
    
    public void setLogistics(Logistics logistics) {
        this.logistics = logistics;
    }
    public String getTrackNumber() {
        return this.trackNumber;
    }
    
    public void setTrackNumber(String trackNumber) {
        this.trackNumber = trackNumber;
    }
    public BigDecimal getPostage() {
        return this.postage;
    }
    
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }
    public String getFromLocation() {
        return this.fromLocation;
    }
    
    public void setFromLocation(String fromLocation) {
        this.fromLocation = fromLocation;
    }
    public String getToLocation() {
        return this.toLocation;
    }
    
    public void setToLocation(String toLocation) {
        this.toLocation = toLocation;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getSignedoffDate() {
        return this.signedoffDate;
    }
    
    public void setSignedoffDate(Date signedoffDate) {
        this.signedoffDate = signedoffDate;
    }
    public String getSignedoffPerson() {
        return this.signedoffPerson;
    }
    
    public void setSignedoffPerson(String signedoffPerson) {
        this.signedoffPerson = signedoffPerson;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getOrderShippments() {
        return this.orderShippments;
    }
    
    public void setOrderShippments(Set orderShippments) {
        this.orderShippments = orderShippments;
    }




}


