package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TrackingApiParams generated by hbm2java
 */
public class TrackingApiParams  implements java.io.Serializable {


     private Short paramId;
     private TrackingApi trackingApi;
     private String paramName;
     private String paramValue;
     private char archvFlag;
     private Date lastUpdate;

    public TrackingApiParams() {
    }

    public TrackingApiParams(TrackingApi trackingApi, String paramName, String paramValue, char archvFlag, Date lastUpdate) {
       this.trackingApi = trackingApi;
       this.paramName = paramName;
       this.paramValue = paramValue;
       this.archvFlag = archvFlag;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getParamId() {
        return this.paramId;
    }
    
    public void setParamId(Short paramId) {
        this.paramId = paramId;
    }
    public TrackingApi getTrackingApi() {
        return this.trackingApi;
    }
    
    public void setTrackingApi(TrackingApi trackingApi) {
        this.trackingApi = trackingApi;
    }
    public String getParamName() {
        return this.paramName;
    }
    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }
    public String getParamValue() {
        return this.paramValue;
    }
    
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
    public char getArchvFlag() {
        return this.archvFlag;
    }
    
    public void setArchvFlag(char archvFlag) {
        this.archvFlag = archvFlag;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


