package dpocket.entity;
// Generated 15/07/2015 2:16:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrackingApi generated by hbm2java
 */
public class TrackingApi  implements java.io.Serializable {


     private Short apiId;
     private Logistics logistics;
     private String baseUrl;
     private short limit;
     private boolean active;
     private Date lastUpdate;
     private Set trackingApiParamses = new HashSet(0);

    public TrackingApi() {
    }

	
    public TrackingApi(Logistics logistics, String baseUrl, short limit, boolean active, Date lastUpdate) {
        this.logistics = logistics;
        this.baseUrl = baseUrl;
        this.limit = limit;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public TrackingApi(Logistics logistics, String baseUrl, short limit, boolean active, Date lastUpdate, Set trackingApiParamses) {
       this.logistics = logistics;
       this.baseUrl = baseUrl;
       this.limit = limit;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.trackingApiParamses = trackingApiParamses;
    }
   
    public Short getApiId() {
        return this.apiId;
    }
    
    public void setApiId(Short apiId) {
        this.apiId = apiId;
    }
    public Logistics getLogistics() {
        return this.logistics;
    }
    
    public void setLogistics(Logistics logistics) {
        this.logistics = logistics;
    }
    public String getBaseUrl() {
        return this.baseUrl;
    }
    
    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl;
    }
    public short getLimit() {
        return this.limit;
    }
    
    public void setLimit(short limit) {
        this.limit = limit;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getTrackingApiParamses() {
        return this.trackingApiParamses;
    }
    
    public void setTrackingApiParamses(Set trackingApiParamses) {
        this.trackingApiParamses = trackingApiParamses;
    }




}


