package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * PaymentId generated by hbm2java
 */
public class VCustomerListId implements java.io.Serializable {

    private Short customerId;
    private String customerName;
    private String phone;
    private String address;
    private String province;
    private String city;
    private String suburb;
    private String postcode;
    private String cardNumber;
    private String filePathFront;
    private String filePathBack;
    private String email;

    public VCustomerListId() {
    }

    public VCustomerListId(Integer orderId) {
        this.customerId = customerId;
    }

    public VCustomerListId(Short customerId, String customerName, String phone, String address, String province, String city, String suburb, String postcode, String cardNumber, String filePathFront, String filePathBack, String email) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.phone = phone;
        this.address = address;
        this.province = province;
        this.city = city;
        this.suburb = suburb;
        this.postcode = postcode;
        this.cardNumber = cardNumber;
        this.filePathFront = filePathFront;
        this.filePathBack = filePathBack;
        this.email = email;
        
    }

    public String getFilePathFront() {
        return filePathFront;
    }

    public void setFilePathFront(String filePathFront) {
        this.filePathFront = filePathFront;
    }

    public String getFilePathBack() {
        return filePathBack;
    }

    public void setFilePathBack(String filePathBack) {
        this.filePathBack = filePathBack;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    
    
    
    public Short getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getSuburb() {
        return suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    

    

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VCustomerListId)) {
            return false;
        }
        VCustomerListId castOther = (VCustomerListId) other;

        return (this.getCustomerId() == castOther.getCustomerId())
                && (this.getCustomerName() == castOther.getCustomerName()) || (this.getCustomerName() != null
                && castOther.getCustomerName() != null && this.getCustomerName().equals(
                        castOther.getCustomerName()))
                 && (this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
                && castOther.getPhone() != null && this.getPhone().equals(
                        castOther.getPhone()))
                 && (this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
                && castOther.getAddress() != null && this.getAddress().equals(
                        castOther.getAddress()))
                && (this.getProvince() == castOther.getProvince()) || (this.getProvince() != null
                && castOther.getProvince() != null && this.getProvince().equals(
                        castOther.getProvince()))
                && (this.getCity() == castOther.getCity()) || (this.getCity() != null
                && castOther.getCity() != null && this.getCity().equals(
                        castOther.getCity()))
                && (this.getSuburb() == castOther.getSuburb()) || (this.getSuburb() != null
                && castOther.getSuburb() != null && this.getSuburb().equals(
                        castOther.getSuburb()))
                && (this.getPostcode() == castOther.getPostcode()) || (this.getPostcode() != null
                && castOther.getPostcode() != null && this.getPostcode().equals(
                        castOther.getPostcode()))
                 && (this.getCardNumber() == castOther.getCardNumber()) || (this.getCardNumber() != null
                && castOther.getCardNumber() != null && this.getCardNumber().equals(
                        castOther.getCardNumber()))
                 && (this.getFilePathFront() == castOther.getFilePathFront()) || (this.getFilePathFront() != null
                && castOther.getFilePathFront() != null && this.getFilePathFront().equals(
                        castOther.getFilePathFront()))
                && (this.getFilePathBack() == castOther.getFilePathBack()) || (this.getFilePathBack() != null
                && castOther.getFilePathBack() != null && this.getFilePathBack().equals(
                        castOther.getFilePathBack()))
                && (this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
                && castOther.getEmail() != null && this.getEmail().equals(
                        castOther.getEmail()))
                ;
    }

    public int hashCode() {
        int result = 17;

        //result = 37 * result + this.getOrderId();
        result = 37 * result
                + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
        result = 37 * result
                + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
        result = 37 * result
                + (getPhone() == null ? 0 : this.getPhone().hashCode());
        result = 37 * result
                + (getPostcode() == null ? 0 : this.getPostcode().hashCode());
        result = 37 * result
                + (getCardNumber() == null ? 0 : this.getCardNumber().hashCode());
        result = 37 * result
                + (getFilePathFront() == null ? 0 : this.getFilePathFront().hashCode());
        result = 37 * result
                + (getFilePathBack() == null ? 0 : this.getFilePathBack().hashCode());
        result = 37 * result
                + (getEmail() == null ? 0 : this.getEmail().hashCode());
        result = 37 * result
                + (getAddress() == null ? 0 : this.getAddress().hashCode());
        result = 37 * result
                + (getProvince() == null ? 0 : this.getProvince().hashCode());
        result = 37 * result
                + (getCity() == null ? 0 : this.getCity().hashCode());
        result = 37 * result
                + (getSuburb() == null ? 0 : this.getSuburb().hashCode());

        return result;
    }
}
