package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA
/**
 * Payment generated by hbm2java
 */
public class VCustomerList implements java.io.Serializable {

    private VOpenOrderId id;

    public VCustomerList() {
    }

    public VCustomerList(VOpenOrderId id) {
        this.id = id;

    }

    public VOpenOrderId getId() {
        return id;
    }

    public void setId(VOpenOrderId id) {
        this.id = id;
    }

    
}
