package dpocket.entity;
// Generated 14/04/2015 11:11:08 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * PaymentId generated by hbm2java
 */
public class VOpenOrderId implements java.io.Serializable {

    private Date orderDate;
    private Integer orderId;
    private String name;
    private BigDecimal amount;
    private String trackNumber;
    private String companyName;
    private Date shippedDate;

    public VOpenOrderId() {
    }

    public VOpenOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public VOpenOrderId(Date orderDate, Integer orderId, String name, BigDecimal amount, String trackNumber, String companyName, Date shippedDate) {
        this.orderDate = orderDate;
        this.orderId = orderId;
        this.name = name;
        this.amount = amount;
        this.trackNumber = trackNumber;
        this.companyName = companyName;
        this.shippedDate = shippedDate;
    }

    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getTrackNumber() {
        return trackNumber;
    }

    public void setTrackNumber(String trackNumber) {
        this.trackNumber = trackNumber;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public Date getShippedDate() {
        return shippedDate;
    }

    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }

    

   

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VOpenOrderId)) {
            return false;
        }
        VOpenOrderId castOther = (VOpenOrderId) other;

        return (this.getOrderDate() == castOther.getOrderDate())
                && (this.getOrderId() == castOther.getOrderId())
                && (this.getName() == castOther.getName()) || (this.getName() != null  
                && castOther.getName() != null && this.getName().equals(  
                castOther.getName()))
                && (this.getTrackNumber() == castOther.getTrackNumber()) || (this.getTrackNumber() != null  
                && castOther.getTrackNumber() != null && this.getTrackNumber().equals(  
                castOther.getTrackNumber()))
                && (this.getCompanyName() == castOther.getCompanyName()) || (this.getCompanyName() != null  
                && castOther.getCompanyName() != null && this.getCompanyName().equals(  
                castOther.getCompanyName()))
                && (this.getAmount() == castOther.getAmount())
                && (this.getShippedDate() == castOther.getShippedDate());
    }

    public int hashCode() {
        int result = 17;

        //result = 37 * result + this.getOrderId();
        result = 37 * result  
                + (getOrderId() == null ? 0 : this.getOrderId().hashCode());  
        result = 37 * result  
                + (getAmount() == null ? 0 : this.getAmount().hashCode());  
        result = 37 * result  
                + (getCompanyName() == null ? 0 : this.getCompanyName().hashCode());  
        result = 37 * result  
                + (getName() == null ? 0 : this.getName().hashCode());  
        result = 37 * result  
                + (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());  
        result = 37 * result  
                + (getShippedDate() == null ? 0 : this.getShippedDate().hashCode());  
        result = 37 * result  
                + (getTrackNumber() == null ? 0 : this.getTrackNumber().hashCode());  
        
        return result;
    }
}
