package dpocket.entity;
// Generated 10/04/2015 10:20:21 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;


/**
 * Customer generated by hbm2java
 */
public class vw_open_order  implements java.io.Serializable {

     
     private Date order_date;
     private Integer order_id;
     private String name;
     private BigDecimal amount;
     private String tracking_numbers;
     private String company_name;
    

    public vw_open_order() {
    }

	
    public vw_open_order(Date order_date, Integer order_id, String name, BigDecimal amount, String tracking_numbers,String company_name ) {
        this.order_date = order_date;
        this.order_id = order_id;
        this.name = name;
        this.amount = amount;
        this.tracking_numbers = tracking_numbers;
        this.company_name = company_name;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }
    
   
    public Integer getCustomerId() {
        return this.order_id;
    }
    
    public void setCustomerId(Integer customerId) {
        this.order_id = customerId;
    }
   
    public String getCustomerName() {
        return this.name;
    }
    
    public void setCustomerName(String customerName) {
        this.name = customerName;
    }
    public String getEmail() {
        return this.tracking_numbers;
    }
    
    public void setEmail(String email) {
        this.tracking_numbers = email;
    }
   
    public Date getCreateDate() {
        return this.order_date;
    }
    
    public void setCreateDate(Date createDate) {
        this.order_date = createDate;
    }
 



}


